# Generated by Django 4.1.6 on 2024-01-16 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bereich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titel')),
                ('beschreibung', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Bereich',
                'verbose_name_plural': 'Bereiche',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titel')),
                ('privat', models.BooleanField(verbose_name='Privat')),
                ('prio', models.IntegerField(verbose_name='Priorität')),
                ('bereich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.bereich', verbose_name='Bereich')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekte',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titel')),
                ('beschreibung', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.project', verbose_name='Projekt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aufgabe',
                'verbose_name_plural': 'Aufgaben',
            },
        ),
    ]
