# Generated by Django 4.1.6 on 2024-01-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bereich',
            old_name='beschreibung',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='bereich',
            new_name='field',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='beschreibung',
            new_name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='cyclical',
            field=models.BooleanField(default=False, verbose_name='Zyklisch'),
        ),
    ]
