# Generated by Django 4.1.6 on 2024-01-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_rename_beschreibung_bereich_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Fertig'),
        ),
    ]
