# Generated by Django 4.1.6 on 2024-06-25 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('privat', models.BooleanField(default=False, verbose_name='Privat')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekte',
            },
        ),
        migrations.CreateModel(
            name='Eintrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50, verbose_name='Tätigkeit')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('begin', models.DateTimeField(auto_now_add=True, verbose_name='Start ')),
                ('end', models.DateTimeField(auto_now=True, verbose_name='Ende')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tagebuch.project', verbose_name='Projekt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eintrag',
                'verbose_name_plural': 'Einträge',
            },
        ),
    ]
