# Generated by Django 4.1.6 on 2024-06-25 10:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tagebuch', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eintrag',
            new_name='Entry',
        ),
    ]
