# Generated by Django 3.1.1 on 2020-10-21 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ausbildung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gruppe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('datStart', models.DateField()),
                ('datEnde', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('timeStart', models.DateTimeField()),
                ('timeEnde', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Teilnehmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('aktiv', models.BooleanField(verbose_name=True)),
                ('ausbildung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ausbildung')),
            ],
        ),
        migrations.CreateModel(
            name='gruppeTN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teilnehmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.teilnehmer')),
                ('gruppe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.gruppe')),
            ],
        ),
        migrations.CreateModel(
            name='Bewertung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abgabe', models.DateTimeField()),
                ('bewertung', models.IntegerField(blank=True)),
                ('kommentar', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.project')),
                ('teilnehmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.teilnehmer')),
            ],
        ),
    ]
