# Generated by Django 3.1.1 on 2020-10-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20201021_0923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fach',
            options={'ordering': ['slug']},
        ),
    ]
