# Generated by Django 3.1.1 on 2020-10-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20201023_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausbildung',
            name='aktiv',
            field=models.BooleanField(default=True, verbose_name=True),
            preserve_default=False,
        ),
    ]
