# Generated by Django 3.1.1 on 2020-10-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_ausbildung_aktiv'),
    ]

    operations = [
        migrations.AddField(
            model_name='teilnehmer',
            name='email',
            field=models.CharField(default='Platzhalter', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teilnehmer',
            name='mobil',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
