# Generated by Django 3.1.1 on 2020-10-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20201026_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausbildung',
            name='aktiv',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='teilnehmer',
            name='aktiv',
            field=models.BooleanField(),
        ),
    ]
