# Generated by Django 3.1.1 on 2020-10-26 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20201026_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ausbildung',
            options={'ordering': ['slug']},
        ),
        migrations.AlterModelOptions(
            name='gruppe',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='gruppetn',
            options={'ordering': ['teilnehmer']},
        ),
        migrations.AlterModelOptions(
            name='teilnehmer',
            options={'ordering': ['name']},
        ),
    ]
