# Generated by Django 3.1.1 on 2020-10-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20201026_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='bewertung',
            name='aktiv',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fach',
            name='aktiv',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gruppe',
            name='aktiv',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gruppetn',
            name='aktiv',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='aktiv',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='teilnehmer',
            name='aktiv',
            field=models.BooleanField(default=True),
        ),
    ]
