# Generated by Django 3.1.1 on 2020-10-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_kanbanproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbanproject',
            name='beschreibung',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kanbanproject',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
