# Generated by Django 3.1.1 on 2020-10-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20201027_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbanproject',
            name='aktiv',
            field=models.BooleanField(default='True'),
        ),
    ]
