# Generated by Django 3.1.1 on 2020-10-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_kanbanproject_aktiv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kanbanproject',
            options={'permissions': [('show_all', 'Kann alle Projekte sehen')]},
        ),
    ]
