# Generated by Django 3.1.1 on 2020-11-22 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_auto_20201122_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gruppe',
            name='datEnde',
        ),
        migrations.RemoveField(
            model_name='gruppe',
            name='datStart',
        ),
    ]
