# Generated by Django 3.1.3 on 2020-11-27 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_auto_20201122_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='TnInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitpunkt', models.DateTimeField(auto_now_add=True)),
                ('info', models.TextField()),
                ('aktiv', models.BooleanField(default=True)),
                ('tn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.teilnehmer')),
            ],
        ),
    ]
