# Generated by Django 3.1.1 on 2020-12-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_projekt_projektetn'),
    ]

    operations = [
        migrations.AddField(
            model_name='projektetn',
            name='offen',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projektetn',
            name='abgabe',
            field=models.DateTimeField(blank=True),
        ),
    ]
