# Generated by Django 3.1.1 on 2020-12-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_auto_20201203_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projektetn',
            name='abgabe',
            field=models.DateTimeField(),
        ),
    ]
