# Generated by Django 3.1.1 on 2020-12-03 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_auto_20201203_1214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bewertung',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
