# Generated by Django 3.1.1 on 2020-12-09 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_auto_20201204_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kanbanbereiche',
            options={'verbose_name_plural': 'Kanban Bereiche'},
        ),
        migrations.AlterModelOptions(
            name='kanbanproject',
            options={'verbose_name_plural': 'Kanban Projekte'},
        ),
        migrations.AlterModelOptions(
            name='kanbanprotokoll',
            options={'verbose_name_plural': 'Kanban Protokolle'},
        ),
        migrations.AlterModelOptions(
            name='projekt',
            options={'verbose_name_plural': 'Projekte'},
        ),
        migrations.AlterModelOptions(
            name='projektetn',
            options={'verbose_name_plural': 'Projekte Teilnehmer'},
        ),
        migrations.AlterModelOptions(
            name='tninfo',
            options={'verbose_name_plural': 'Teilnehmer Infos'},
        ),
        migrations.AddField(
            model_name='projekt',
            name='bis',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
