# Generated by Django 3.1.1 on 2020-12-09 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_auto_20201209_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projekt',
            name='bis',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
