# Generated by Django 3.1.7 on 2021-03-28 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0030_auto_20201209_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mitarbeit_thema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now=True)),
                ('thema', models.CharField(default='', max_length=255)),
                ('gruppe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.gruppe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mitarbeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit', models.DateTimeField(auto_now=True)),
                ('tn_inaktiv', models.BooleanField(default=False)),
                ('tn_abwesend', models.BooleanField(default=False)),
                ('thema_erledigt', models.BooleanField(default=True)),
                ('kommentar', models.CharField(default='', max_length=255)),
                ('thema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.mitarbeit_thema')),
                ('tn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.teilnehmer')),
            ],
        ),
    ]
