# Generated by Django 3.1.1 on 2021-03-30 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_auto_20210329_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeit',
            name='gruppe',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app1.gruppe'),
            preserve_default=False,
        ),
    ]
