# Generated by Django 3.1.1 on 2021-03-30 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_remove_teilnehmer_gruppe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitarbeit',
            name='gruppe',
        ),
        migrations.AddField(
            model_name='teilnehmer',
            name='gruppe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.gruppe'),
        ),
    ]
