# Generated by Django 3.2.4 on 2021-06-23 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0036_auto_20210623_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Essenanmeldung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('gemeldet', models.DateTimeField(auto_now_add=True)),
                ('anzahl_tn', models.IntegerField()),
                ('anzahl_essen', models.IntegerField()),
                ('gemeldet_durch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('gruppe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.gruppe')),
            ],
        ),
    ]
