# Generated by Django 3.2.4 on 2021-10-07 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_essenanmeldung'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ausbilder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktiv', models.BooleanField()),
                ('anrede', models.CharField(max_length=50)),
                ('vorname', models.CharField(max_length=50)),
                ('nachname', models.CharField(max_length=50)),
                ('kuerzel', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='PlanFarbe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farbe', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlanZeiten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('einheit', models.IntegerField()),
                ('von', models.CharField(max_length=10)),
                ('bis', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Raum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standort', models.CharField(max_length=50)),
                ('bezeichnung', models.CharField(max_length=50)),
                ('groesse', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jahr', models.IntegerField()),
                ('kw', models.IntegerField()),
                ('tag', models.IntegerField()),
                ('fach', models.CharField(max_length=50)),
                ('ausbilder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ausbilder')),
                ('einheit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.planzeiten')),
                ('farbe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.planfarbe')),
                ('raum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.raum')),
            ],
        ),
        migrations.AddField(
            model_name='gruppe',
            name='raum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.raum'),
        ),
    ]
