# Generated by Django 3.2.4 on 2021-10-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_auto_20211007_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausbilder',
            name='aktiv',
            field=models.BooleanField(default=True),
        ),
    ]
