# Generated by Django 4.1.6 on 2023-02-04 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app1", "0042_anwesenheit_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Add",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zahl1", models.IntegerField()),
                ("zahl2", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="essenanmeldung",
            name="gemeldet_durch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="essenanmeldung",
            name="gruppe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app1.gruppe"
            ),
        ),
    ]
