# Generated by Django 4.1.6 on 2023-09-04 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0043_add_alter_essenanmeldung_gemeldet_durch_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add',
        ),
        migrations.AddField(
            model_name='gruppe',
            name='sprecher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Gruppensprecher', to='app1.teilnehmer', verbose_name='Gruppensprecher'),
        ),
    ]
